sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
notifications:
  email: false
node_js:
  - 10
  - 8
env: 
  matrix:
    - REACT_VERSION="^16.3.0"
    - REACT_VERSION=">=16.0.0 <16.3.0"
    - REACT_VERSION="^15.4.0"
    - REACT_VERSION=">=15.0.0 <15.4.0"
    - REACT_VERSION="^0.14"
    - REACT_VERSION="latest"
install: 
  - npm install --no-save "react@${REACT_VERSION}"
  - npm install
  - npm ls react
script:
  - npm run validate
after_success: kcd-scripts travis-after-success
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
