sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
notifications:
  email: false
node_js:
  - 10
  - 8
  - 6
install: npm install
script:
  - kcd-scripts validate lint,test:cover,build-and-test
after_success: kcd-scripts travis-after-success
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
