sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
notifications:
  email: false
node_js: '8'
install: npm install
script:
  - kcd-scripts validate lint,test:cover,build-and-test
after_success: kcd-scripts travis-after-success
